### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by dgotrik** [crorvick/outguess#1]
Outguess leaves a signature in file headers after embedding information.

Vulnerability

**Comment by crorvick** [comment]
What is the signature?

**Comment by dgotrik** [comment]
Outguess doesn't preserve the image header, and if you do ' hexdump {image}.jpg | grep CDEF ' you'll see what I mean

**Comment by hoijui** [comment]
I would say you could close this issue, as I "copied" it over to this (supposedly) more maintained fork of outguess:

<https://github.com/resurrecting-open-source-projects/outguess>

**Comment by crorvick** [comment]
Please see @hoijui's repo for a possible future fix?  Or send a patch that way?
