### ISSUE TITLE
Duplicate project

### ISSUE THREAD

**Issue by hoijui** [crorvick/outguess#2]
hey! :-)
just wanted to say that there is an other "fork" of outguess here:
<https://github.com/resurrecting-open-source-projects/outguess>

I made sure it contains all your changes, and it does contain quite some more (mostly minor fixes, as of now).

Would you like to consolidate somehow... deduplicate?

**Comment by crorvick** [comment]
On Tue, Apr 14, 2020 at 11:38:44AM -0700, hoijui wrote:
> hey! :-)
> just wanted to say that there is an other "fork" of outguess here:
> <https://github.com/resurrecting-open-source-projects/outguess>
> 
> I made sure it contains all your changes, and it does contain quite some more (mostly minor fixes, as of now).
> 
> Would you like to consolidate somehow... deduplicate?

Sure, I'm not doing anything active with it anymore so I can just add a
reference to your repo.  Thanks for the heads up!

Chris

**Comment by hoijui** [comment]
cool, thank you! :-)

> ... for possibly a better option.

perfect! :D
